baseURL = "https://tferazzi.github.io"
title = "Tobias Ferazzi"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "bw"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Tobias Ferazzi"
description = "Tobias Ferazzi's website"
keywords = "blog,developer,personal"
info = ["IT Solution and Cloud Architect"]
avatarURL = "images/mrbean.jpeg"
dateFormat = "January 2, 2006"
since = 2019
rtl = false
colorScheme = "dark"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/tferazzi/"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/tobias-ferazzi-a83847179/"

[[params.social]]
name = "Xing"
icon = "fa fa-2x fa-xing"
weight = 4
url = "https://www.xing.com/profile/Tobias_Ferazzi/"
